document.addEventListener("DOMContentLoaded",()=>{
const PRICE_API="https://strike-pulse-relay.onrender.com/api/prices",OPTION_API="https://strike-pulse-relay.onrender.com/api/nifty-option-chain",API_BASE="https://strike-pulse-relay.onrender.com/api";
let currentSymbol="NIFTY";const last={};const $=id=>document.getElementById(id);
const buttons=document.querySelectorAll(".sp-symbol-btn"),selectedSymbol=$("spSelectedSymbol"),expiry=$("spExpiry"),spot=$("spSpot"),atm=$("spATM"),callOI=$("spCallOI"),putOI=$("spPutOI"),pcr=$("spPCR"),maxPain=$("spMaxPain"),tableTitle=$("spTableTitle"),updated=$("spUpdated"),optionBody=$("spOptionBody"),searchInput=$("spSymbolSearch"),searchButton=$("spSearchBtn"),searchResults=$("spSearchResults");
function india(){return new Date(new Date().toLocaleString("en-US",{timeZone:"Asia/Kolkata"}))}
function num(v,d=0){if(v==null||v===""||isNaN(Number(v)))return"--";return Number(v).toLocaleString("en-IN",{minimumFractionDigits:d,maximumFractionDigits:d})}
function open(){const p=new Intl.DateTimeFormat("en-IN",{timeZone:"Asia/Kolkata",weekday:"short",hour:"2-digit",minute:"2-digit",hour12:false}).formatToParts(new Date()),g=t=>p.find(x=>x.type===t)?.value||"",day={Mon:1,Tue:2,Wed:3,Thu:4,Fri:5,Sat:6,Sun:0}[g("weekday")],m=+g("hour")*60+ +g("minute");return day>=1&&day<=5&&m>=555&&m<930}
function status(){const o=open(),t=o?"OPEN":"CLOSED";document.querySelectorAll(".sp-market-status").forEach(e=>{e.classList.remove("sp-live","sp-open","sp-closed");e.classList.add(o?"sp-open":"sp-closed");e.textContent=t});const tl=document.querySelector(".sp-table-live");if(tl){tl.classList.remove("sp-live","sp-open","sp-closed");tl.classList.add(o?"sp-open":"sp-closed");const x=tl.querySelector("#spTableStatus");if(x)x.textContent=t}document.querySelectorAll("#spMarketStatus").forEach(e=>e.textContent=t)}
function card(m,p,c,apiUpdated){const e=document.querySelector(`.sp-price[data-market="${m}"]`);if(!e)return;if(p==null){e.textContent="--";return}e.textContent=num(p,2);const q=e.closest(".sp-market-card")||e.closest(".wp-block-column")||e.parentElement,ch=q?.querySelector(".sp-market-change,.sp-change"),u=q?.querySelector(".sp-updated");if(ch&&c!=null){const n=Number(c);ch.textContent=(n>0?"▲ +":n<0?"▼ ":"● ")+n.toFixed(2)+"%"}if(u){const d=apiUpdated?new Date(apiUpdated):india();u.textContent="Updated "+(isNaN(d.getTime())?india():d).toLocaleTimeString("en-IN",{hour:"2-digit",minute:"2-digit",second:"2-digit"})}}
async function prices(){try{const r=await fetch(PRICE_API+"?t="+Date.now(),{cache:"no-store"});if(!r.ok)throw Error("Price API HTTP "+r.status);const j=await r.json();const s=j.data&&typeof j.data==="object"?j.data:j;const markets=j.markets&&typeof j.markets==="object"?j.markets:{};["nifty","banknifty","finnifty","vix"].forEach(k=>{const market=markets[k]||{};const p=s[k]??market.price??last[k];const c=s[k+"Change"]??market.change??last[k+"Change"];card(k,p,c,j.updated||s.updated);last[k]=p;last[k+"Change"]=c});status()}catch(e){console.error("STRIKE PULSE PRICE ERROR",e)}}
const val=(o,ks)=>{for(const k of ks)if(o&&o[k]!=null)return o[k];return null};
function main(d){return d?.data&&typeof d.data==="object"?d.data:d?.result&&typeof d.result==="object"?d.result:d||{}}
function normalize(i){const c=i?.ce||i?.CE||i?.call||{},p=i?.pe||i?.PE||i?.put||{},side=o=>({oi:val(o,["oi","OI","openInterest"]),oiChange:val(o,["oiChange","changeOI","changeinOpenInterest"]),volume:val(o,["volume","Volume","totalTradedVolume"]),iv:val(o,["iv","IV","impliedVolatility"]),ltp:val(o,["ltp","LTP","lastPrice"])});return{strike:val(i,["strike","strikePrice","strike_price"]),call:side(c),put:side(p)}}
function rows(m,d){const a=[m.options,m.optionChain,m.records,m.rows,m.chain,d?.options,d?.optionChain,d?.records,d?.rows,d?.chain].find(Array.isArray)||[];return a.map(normalize)}
function summary(m){return{symbol:m.symbol||currentSymbol,spot:m.spot??m.spotPrice??m.underlyingValue,atmStrike:m.atmStrike??m.atm,expiry:m.expiry??m.expiryDate,callOI:m.callOI??m.totalCallOI??m.totalCEOI,putOI:m.putOI??m.totalPutOI??m.totalPEOI,pcr:m.pcr??m.PCR??m.putCallRatio,maxPain:m.maxPain??m.maxpain??m.max_pain}}
function loading(){if(expiry)expiry.textContent="Loading...";[spot,atm,callOI,putOI,pcr,maxPain].forEach(e=>{if(e)e.textContent="--"});if(updated)updated.textContent="Updating live data...";if(optionBody)optionBody.innerHTML='<tr><td colspan="11" class="sp-table-loading">Loading '+currentSymbol+' option chain...</td></tr>'}
function renderExpiry(m){if(expiry){const x=val(m,["expiries","expiryDates","expiry","expirationDates"]);expiry.textContent=Array.isArray(x)?(x.find(Boolean)||"Live"):(x||"Live")}}
function update(d){const a=d.atmStrike??d.atm;if(spot&&d.spot!=null)spot.textContent=num(d.spot,2);if(atm&&a!=null)atm.textContent=num(a);if(callOI&&d.callOI!=null)callOI.textContent=num(d.callOI);if(putOI&&d.putOI!=null)putOI.textContent=num(d.putOI);if(pcr&&d.pcr!=null)pcr.textContent=(+d.pcr).toFixed(2);if(maxPain&&d.maxPain!=null)maxPain.textContent=num(d.maxPain);if(selectedSymbol)selectedSymbol.textContent=(d.symbol||currentSymbol).toUpperCase();if(tableTitle)tableTitle.textContent=currentSymbol+" Option Chain";if(updated)updated.textContent="Updated "+india().toLocaleTimeString("en-IN",{hour:"2-digit",minute:"2-digit",second:"2-digit"})}
function render(rows,a){if(!optionBody)return;if(!rows.length){optionBody.innerHTML='<tr><td colspan="11" class="sp-table-loading">No option-chain data available</td></tr>';return}optionBody.innerHTML=rows.map(r=>{const c=r.call||{},p=r.put||{},cc=+(c.oiChange||0),pc=+(p.oiChange||0),at=+r.strike===+a;return`<tr class="${at?"atm-row sp-chain-atm":""}"><td>${num(c.oi)}</td><td class="${cc>0?"sp-positive":cc<0?"sp-negative":""}">${cc>=0?"+":""}${num(cc)}</td><td>${num(c.volume)}</td><td>${num(c.iv,2)}</td><td>${num(c.ltp,2)}</td><td class="sp-chain-strike">${num(r.strike)}</td><td>${num(p.ltp,2)}</td><td>${num(p.iv,2)}</td><td>${num(p.volume)}</td><td class="${pc>0?"sp-positive":pc<0?"sp-negative":""}">${pc>=0?"+":""}${num(pc)}</td><td>${num(p.oi)}</td></tr>`}).join("")}
async function load(symbol){currentSymbol=symbol.toUpperCase();buttons.forEach(b=>b.classList.toggle("active",(b.dataset.symbol||"").toUpperCase()===currentSymbol));if(selectedSymbol)selectedSymbol.textContent=currentSymbol;if(tableTitle)tableTitle.textContent=currentSymbol+" Option Chain";loading();try{const base=currentSymbol==="NIFTY"?OPTION_API:API_BASE+"/nifty-option-chain",r=await fetch(base+"?symbol="+encodeURIComponent(currentSymbol)+"&t="+Date.now(),{cache:"no-store"}),j=await r.json();if(j.success===false)throw Error(j.error||"Option API failed");const m=main(j),rs=rows(m,j);if(!rs.length)throw Error("Option rows not found");const d=summary(m);update(d);renderExpiry(m);render(rs,d.atmStrike);status()}catch(e){console.error("STRIKE PULSE OPTION ERROR",e);if(optionBody)optionBody.innerHTML='<tr><td colspan="11" class="sp-table-loading">Live data unavailable</td></tr>';if(updated)updated.textContent="Live data unavailable"}}
buttons.forEach(b=>b.addEventListener("click",e=>{e.preventDefault();if(b.dataset.symbol)load(b.dataset.symbol)}));
const syms=[{s:"NIFTY",n:"NIFTY 50"},{s:"BANKNIFTY",n:"BANK NIFTY"},{s:"FINNIFTY",n:"FIN NIFTY"}];
if(searchInput)searchInput.addEventListener("input",()=>{const q=searchInput.value.trim().toUpperCase();if(!q){if(searchResults)searchResults.style.display="none";return}const m=syms.filter(x=>x.s.includes(q)||x.n.includes(q));if(!searchResults||!m.length){if(searchResults)searchResults.style.display="none";return}searchResults.innerHTML=m.map(x=>`<div class="sp-search-item" data-symbol="${x.s}">${x.n}</div>`).join("");searchResults.style.display="block";searchResults.querySelectorAll(".sp-search-item").forEach(x=>x.onclick=()=>{searchInput.value=x.textContent;searchResults.style.display="none";load(x.dataset.symbol)})});
if(searchButton)searchButton.onclick=e=>{e.preventDefault();const q=(searchInput?.value||"").toUpperCase(),s=q.includes("BANK")?"BANKNIFTY":q.includes("FIN")?"FINNIFTY":q.includes("NIFTY")?"NIFTY":null;if(s)load(s)};
document.addEventListener("click",e=>{if(searchResults&&!searchResults.contains(e.target)&&e.target!==searchInput)searchResults.style.display="none"});
status();prices();load("NIFTY");setInterval(prices,2000);setInterval(()=>load(currentSymbol),30000);setInterval(status,1000);console.log("STRIKE PULSE external JS loaded")
});
