const express = require("express");
const app = express();
const PORT = process.env.PORT || 10000;
const NSE = "https://www.nseindia.com";
const HEADERS = {"User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/137.0.0.0 Safari/537.36","Accept-Language":"en-US,en;q=0.9","Accept":"application/json,text/plain,*/*","Referer":"https://www.nseindia.com/option-chain"};
app.use((req,res,next)=>{res.setHeader("Access-Control-Allow-Origin","*");res.setHeader("Access-Control-Allow-Methods","GET,OPTIONS");res.setHeader("Access-Control-Allow-Headers","Content-Type");res.setHeader("Cache-Control","no-store");if(req.method==="OPTIONS")return res.sendStatus(204);next();});
let cookies="",cookieAt=0;
const cache=new Map(), pending=new Map();
const price={success:true,nifty:null,niftyChange:null,banknifty:null,bankniftyChange:null,finnifty:null,finniftyChange:null,vix:null,vixChange:null,updated:null,source:"nse"};
const num=v=>Number.isFinite(Number(v))?Number(v):null;
function getCookies(r){if(typeof r.headers.getSetCookie==="function")return r.headers.getSetCookie().map(x=>x.split(";")[0]).filter(Boolean).join("; ");const x=r.headers.get("set-cookie")||"";return x?x.split(/,(?=[^;,=]+=[^;,]+)/).map(v=>v.split(";")[0].trim()).filter(Boolean).join("; "):"";}
async function warm(force=false){if(!force&&cookies&&Date.now()-cookieAt<240000)return cookies;let r=await fetch(NSE+"/",{headers:HEADERS});cookies=getCookies(r);try{r=await fetch(NSE+"/option-chain",{headers:{...HEADERS,Accept:"text/html"}});const c=getCookies(r);if(c)cookies=c;}catch{}cookieAt=Date.now();return cookies;}
async function nse(path,retry=true){try{const c=await warm(false);const r=await fetch(NSE+path,{headers:{...HEADERS,...(c?{Cookie:c}:{}),"X-Requested-With":"XMLHttpRequest"}});const t=await r.text();if([401,403,404].includes(r.status)&&retry){cookies="";await warm(true);return nse(path,false);}if(!r.ok)throw Error(`NSE HTTP ${r.status}: ${t.slice(0,140)}`);return JSON.parse(t);}catch(e){if(retry){cookies="";try{await warm(true);const r=await fetch(NSE+path,{headers:{...HEADERS,Cookie:cookies,"X-Requested-With":"XMLHttpRequest"}});const t=await r.text();if(r.ok)return JSON.parse(t);}catch{}}throw e;}}
async function updatePrices(){try{const b=await nse("/api/allIndices");const a=b?.data||[];const find=x=>a.find(v=>String(v?.index||"").trim()===x);for(const [k,x] of Object.entries({nifty:"NIFTY 50",banknifty:"NIFTY BANK",finnifty:"NIFTY FINANCIAL SERVICES",vix:"INDIA VIX"})){const z=find(x);if(z){price[k]=num(z.last);price[k+"Change"]=num(z.percentChange);}}price.updated=new Date().toISOString();}catch(e){console.log("price",e.message);}}
function normalize(body,expiry){const root=body?.records||body?.data||body;const data=Array.isArray(root?.data)?root.data:[];const map=new Map();for(const x of data){if(expiry&&x.expiryDate&&x.expiryDate!==expiry)continue;const strike=num(x.strikePrice);if(strike==null)continue;if(!map.has(strike))map.set(strike,{strike,ce:null,pe:null});if(x.CE)map.get(strike).ce=x.CE;if(x.PE)map.get(strike).pe=x.PE;}return {spot:num(root?.underlyingValue??body?.underlyingValue),rows:[...map.values()].sort((a,b)=>a.strike-b.strike)};}
function maxPain(rows){let best=null,loss=Infinity;for(const c of rows){let l=0;for(const x of rows){const co=x.ce?.openInterest||0,po=x.pe?.openInterest||0;if(c.strike>x.strike)l+=co*(c.strike-x.strike);if(c.strike<x.strike)l+=po*(x.strike-c.strike);}if(l<loss){loss=l;best=c.strike;}}return best;}
async function contractInfo(symbol){const b=await nse(`/api/option-chain-contract-info?symbol=${encodeURIComponent(symbol)}`);const r=b?.records||b?.data||b;return [...new Set(r?.expiryDates||b?.expiryDates||[])];}
async function loadChain(symbol,expiry,full=true){symbol=String(symbol||"NIFTY").toUpperCase();let expiries=[];try{expiries=await contractInfo(symbol);}catch(e){console.log("expiry",symbol,e.message);}const exp=expiry||expiries[0]||null;const type=["NIFTY","BANKNIFTY","FINNIFTY","MIDCPNIFTY","NIFTYNXT50"].includes(symbol)?"Indices":"Equity";const base=`/api/option-chain-v3?type=${type}&symbol=${encodeURIComponent(symbol)}`;const paths=[];if(exp)paths.push(base+`&expiry=${encodeURIComponent(exp)}`);paths.push(base);if(exp)paths.push(`/api/option-chain-${type==="Indices"?"indices":"equities"}?symbol=${encodeURIComponent(symbol)}&expiry=${encodeURIComponent(exp)}`);paths.push(`/api/option-chain-${type==="Indices"?"indices":"equities"}?symbol=${encodeURIComponent(symbol)}`);let last;for(const path of paths){try{const body=await nse(path);const z=normalize(body,exp);if(!z.rows.length)throw Error("No option rows");const spot=z.spot||(symbol==="NIFTY"?price.nifty:null);if(!spot)throw Error("Spot unavailable");let ai=0,d=Infinity;z.rows.forEach((x,i)=>{const q=Math.abs(x.strike-spot);if(q<d){d=q;ai=i;}});const source=full?z.rows:z.rows.slice(Math.max(0,ai-5),ai+6);const rows=source.map(x=>({strike:x.strike,ce:{ltp:num(x.ce?.lastPrice),change:num(x.ce?.change),oi:num(x.ce?.openInterest),oiChange:num(x.ce?.changeinOpenInterest),volume:num(x.ce?.totalTradedVolume),iv:num(x.ce?.impliedVolatility),bid:num(x.ce?.bidprice),ask:num(x.ce?.askPrice)},pe:{ltp:num(x.pe?.lastPrice),change:num(x.pe?.change),oi:num(x.pe?.openInterest),oiChange:num(x.pe?.changeinOpenInterest),volume:num(x.pe?.totalTradedVolume),iv:num(x.pe?.impliedVolatility),bid:num(x.pe?.bidprice),ask:num(x.pe?.askPrice)}}));const callOI=rows.reduce((s,x)=>s+(x.ce.oi||0),0),putOI=rows.reduce((s,x)=>s+(x.pe.oi||0),0);return {success:true,source:"nse",symbol,spot,expiry:exp,expiries,atm:z.rows[ai].strike,atmStrike:z.rows[ai].strike,callOI,putOI,callOIChange:rows.reduce((s,x)=>s+(x.ce.oiChange||0),0),putOIChange:rows.reduce((s,x)=>s+(x.pe.oiChange||0),0),pcr:callOI?putOI/callOI:null,maxPain:maxPain(z.rows),totalStrikes:z.rows.length,rows,updated:new Date().toISOString()};}catch(e){last=e;console.log("option",symbol,e.message);}}throw last||Error("Option chain unavailable");}
const POPULAR=["RELIANCE","HDFCBANK","ICICIBANK","SBIN","INFY","TCS","BHARTIARTL","ITC","LT","AXISBANK","KOTAKBANK","M&M","BAJFINANCE","HINDUNILVR","MARUTI","SUNPHARMA","ADANIENT","ADANIPORTS","NTPC","POWERGRID","TATAMOTORS","TATASTEEL","JSWSTEEL","HCLTECH","WIPRO","TECHM","COALINDIA","ONGC","BEL","TRENT","ETERNAL","INDUSINDBK","BANKBARODA","PNB","CANBK","RECLTD","PFC","IRFC","HAL","DLF","VBL","PIDILITIND","ASIANPAINT","ULTRACEMCO","GRASIM","NESTLEIND","TITAN","BAJAJFINSV","BAJAJ-AUTO","EICHERMOT","HEROMOTOCO","TVSMOTOR","DRREDDY","CIPLA","APOLLOHOSP","DIVISLAB","BPCL","IOC","GAIL","VEDL","HINDALCO","JINDALSTEL","SAIL","TATAPOWER","AMBUJACEM","ACC","ABB","SIEMENS","INDIGO","IRCTC","LICI","HDFCLIFE","SBILIFE","MOTHERSON","DABUR","COLPAL","GODREJCP","ICICIPRULI","CHOLAFIN","SHRIRAMFIN","OFSS","PERSISTENT","COFORGE","MPHASIS","LTIM","BHEL","NHPC","IEX","IDEA","YESBANK"];
app.get("/",(q,r)=>r.json({success:true,message:"Strike Pulse Relay is running",source:"nse",lastUpdate:price.updated}));
app.get("/api/prices",async(q,r)=>{if(!price.nifty)await updatePrices();r.json({...price,data:price});});
app.get("/api/option-symbols",(q,r)=>{const s=String(q.query.q||"").toUpperCase().trim();r.json({success:true,symbols:POPULAR.filter(x=>!s||x.includes(s)).slice(0,40)});});
app.get("/api/option-expiries",async(q,r)=>{try{const symbol=String(q.query.symbol||"NIFTY").toUpperCase();r.json({success:true,symbol,expiries:await contractInfo(symbol)});}catch(e){r.status(500).json({success:false,error:e.message});}});
app.get("/api/option-chain",async(q,r)=>{const symbol=String(q.query.symbol||"NIFTY").toUpperCase(),expiry=q.query.expiry?String(q.query.expiry):null,full=String(q.query.full??"true")!=="false",key=`${symbol}|${expiry||"AUTO"}|${full}`;const c=cache.get(key);if(c&&Date.now()-c.at<10000)return r.json(c.data);if(pending.has(key))try{return r.json(await pending.get(key));}catch(e){return r.status(500).json({success:false,error:e.message});}const p=Promise.race([loadChain(symbol,expiry,full),new Promise((_,rej)=>setTimeout(()=>rej(Error("Option chain upstream timeout")),25000))]);pending.set(key,p);try{const data=await p;cache.set(key,{at:Date.now(),data});r.json(data);}catch(e){r.status(500).json({success:false,error:e.message});}finally{pending.delete(key);}});
app.get("/api/nifty-option-chain",async(q,r)=>{try{r.json(await loadChain("NIFTY",q.query.expiry?String(q.query.expiry):null,false));}catch(e){r.status(500).json({success:false,error:e.message});}});
updatePrices();setInterval(updatePrices,15000);app.listen(PORT,"0.0.0.0",()=>console.log("Strike Pulse Relay running on "+PORT));
